language: go
go:
    - 1.9.x
    - 1.10.x
    - 1.11.x
before_install:
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
install:
    - go get github.com/xtaci/kcptun/kcpclient
    - go get github.com/xtaci/kcptun/kcpserver
before_script:
script:
    - cd $HOME/gopath/src/github.com/xtaci/kcptun/kcpclient
    - $HOME/gopath/bin/goveralls -service=travis-ci
    - cd $HOME/gopath/src/github.com/xtaci/kcptun/kcpserver
    - $HOME/gopath/bin/goveralls -service=travis-ci
    - exit 0
